export type JournalEntry = {
  id: number;
  title: string;
  paragraphs: string[];
};

export const journalEntries: JournalEntry[] = [
  {
    id: 1,
    title: "My Personality",
    paragraphs: [
      `I would say that I am basically an introverted person.`,
      `I like spending time by myself at home. I feel comfortable in quiet places, and I usually prefer having some quiet time rather than being in a large, noisy group.`,
      `I have quite a few indoor hobbies, such as reading and drawing. When I find something I like, I tend to spend a lot of time on it and try to learn more about it.`,
      `I'm not really the kind of person who actively goes out and looks for new experiences. I usually feel more comfortable staying at home and doing something I enjoy.`,
      `At the same time, when I look back on my university life, I sometimes wish I had been a little more active. I think I could have tried more things and taken action more often.`,
      `So, I don't think being introverted is necessarily a bad thing. I like spending time alone, but I also think it's important to actually take action when there is something I'm interested in.`,
    ],
  },
  {
    id: 2,
    title: "My Daily Routine",
    paragraphs: [
      `My daily routine is not very fixed these days. My sleeping and waking times change quite a bit, so I sometimes get up relatively late.`,
      `When I was in high school, however, I sometimes got up extremely early. There were even times when I woke up at around three in the morning. I don't do that anymore.`,
      `One interesting exception is Sunday. This year, I have been watching Precure in real time, so I sometimes get up relatively early on Sunday morning.`,
      `After I get up, I usually take things slowly for a while. Then I take a bath and write in my notebook.`,
      `I have been keeping this kind of record for quite a long time. I write down things like what time I got up and what time I went to bed the previous night.`,
      `During the day, I usually read books, draw, watch VTubers, or use my computer.`,
      `Ideally, I would like to spend more time quietly doing things I enjoy, especially reading and drawing.`,
    ],
  },
  {
    id: 3,
    title: "My Hobbies",
    paragraphs: [
      `My main hobbies are reading, drawing, and watching VTubers.`,
      `I have been interested in drawing since I was a child. These days, I don't just draw for fun. I also study things like human anatomy and backgrounds so that I can improve my skills.`,
      `I also read a lot of books. I read many different kinds of books, including novels, history, economics, science, and technology. I don't really have one particular genre that I always read.`,
      `Another hobby of mine is watching VTubers. I've been watching them for many years, and I especially enjoy long live streams.`,
      `I think my hobbies have one thing in common. I like things that I can spend a long time exploring.`,
      `For example, when I find an interesting book or an interesting topic, I don't want to just learn the basics and move on. I like going deeper and discovering new things.`,
      `That's probably one of the main characteristics of my hobbies.`,
    ],
  },
  {
    id: 4,
    title: "How I Started Drawing",
    paragraphs: [
      `I have been drawing since I was very young. I remember drawing a lot when I was in kindergarten.`,
      `When I was in elementary school, I often drew pictures in notebooks. I also drew things that looked like manga, and I sometimes copied characters from manga.`,
      `When I was in junior high school, I started thinking about making my own manga. I came up with characters and story settings, but I almost never actually finished a manga.`,
      `At that time, I mostly drew characters from the front. I didn't really know much about anatomy or how to draw different poses.`,
      `Then, when I entered high school, I stopped drawing very much.`,
      `I started drawing again after entering university. This time, however, I approached drawing differently. Instead of just drawing whatever I wanted, I started using books and studying how the human body and backgrounds are structured.`,
      `That made drawing much more interesting to me, because I could actually see myself improving.`,
    ],
  },
  {
    id: 5,
    title: "Why I Like Drawing Characters",
    paragraphs: [
      `I've liked drawing characters since I was a child.`,
      `When I was in elementary school, I often copied characters from manga. I think I may have already had the feeling that I wanted to draw my own manga someday.`,
      `What I especially like about drawing characters is their expressions and poses.`,
      `For example, I like thinking about how a character should stand, what kind of expression they should have, and what they might be feeling in that situation.`,
      `In the past, I mostly drew characters individually. But now I want to go further than that.`,
      `I'd like to be able to draw several characters together and show their relationships through their poses and expressions.`,
      `For example, instead of just drawing two characters standing next to each other, I'd like to make it clear that they are friends, or that they have a particular relationship.`,
      `I think that's much more difficult, but it's also one of the things I want to learn.`,
    ],
  },
  {
    id: 6,
    title: "My Reading History",
    paragraphs: [
      `I read a pretty wide range of books.`,
      `I read novels, history, economics, science, technology, and general nonfiction. Sometimes I read a book and realize that I'm not even sure what genre it belongs to.`,
      `When I was in elementary school, I didn't read many novels. I mostly read manga.`,
      `In junior high school, I started reading novels by Yoshiki Tanaka. At first, reading long passages was difficult because I wasn't used to reading that much text. But gradually, I got used to it.`,
      `In high school, I started reading a lot more. I bought my first book from the shinsho, or paperback nonfiction, section, and I really enjoyed it.`,
      `After that, I became interested in many different subjects, including history, economics, science, and technology.`,
      `Recently, I've been particularly interested in economics, but I still like reading many different kinds of books.`,
      `I especially like books that make me think, "Oh, so that's why!" I also like books that I want to read again after finishing them.`,
    ],
  },
  {
    id: 7,
    title: "How I Became Interested in Computers",
    paragraphs: [
      `My interest in computers actually started quite unexpectedly.`,
      `When I was in junior high school, I wasn't interested in computers at all. In technology class, we learned various technical subjects. We didn't really use computers, but I somehow developed the impression that engineering and technical subjects were difficult.`,
      `I also didn't have many opportunities to use a computer at home, so I didn't think of myself as a computer person.`,
      `Even in high school, I had very little interest in computers. I actually thought of myself as more of an analog person. I didn't even really understand what a Google account was.`,
      `Then, one day, I happened to pick up a book about information security. I started reading it, and surprisingly, I found it really interesting.`,
      `That was the turning point.`,
      `After that, I gradually became interested in computers and information technology.`,
      `I originally wanted to study science at university, but I wasn't accepted into a science department, so I ended up studying information engineering.`,
      `In the end, that turned out to be a good thing, because I discovered many interesting areas that I didn't even know about in high school.`,
    ],
  },
  {
    id: 8,
    title: "Technology I Became Interested in at University",
    paragraphs: [
      `At university, I became interested in many different areas of technology.`,
      `One of the areas I found particularly interesting was computer vision. I had never heard of it before university, so it was interesting to discover that computers could be used to analyze images and understand visual information.`,
      `I also became interested in deep learning and AI. These are related to my current graduation research as well.`,
      `Besides that, I've studied programming and web development. I've also had some experience with game development.`,
      `More recently, I've become interested in control systems and embedded systems. I'm interested in both hardware and software, so I find systems that combine the two especially interesting.`,
      `One thing I like about information engineering is that it covers such a wide range of topics.`,
      `When I entered university, I didn't really know what kind of field I wanted to study. But during university, I discovered many areas that I had never heard of before.`,
      `That's probably one of the best things about studying information engineering.`,
    ],
  },
  {
    id: 9,
    title: "My University Life",
    paragraphs: [
      `There are several things I think went well during my university life.`,
      `First, I was able to spend a lot of time developing my hobbies. I continued reading, and I started taking drawing more seriously.`,
      `For drawing, I began using books and studying things like anatomy and backgrounds. Instead of relying only on intuition, I started thinking about the structure behind what I was drawing.`,
      `I also learned a lot about information technology. When I entered university, I didn't know much about computer science, but I gradually discovered areas such as computer vision, deep learning, programming, and web development.`,
      `At the same time, I think I could have been more active.`,
      `I don't necessarily mean that I should have traveled more or joined a club. I mean that I could have taken action more often when I became interested in something.`,
      `So I don't think my university life was a failure. I was able to develop things that I really like.`,
      `But I think I could have balanced that with a little more action and exploration.`,
    ],
  },
  {
    id: 10,
    title: "My Favorite Anime and Manga",
    paragraphs: [
      `I've liked anime and manga for a long time.`,
      `One of my favorite series is World Trigger. I've been following it since I was in elementary school, so it's a series I've enjoyed for a very long time.`,
      `I also like The Heroic Legend of Arslan.`,
      `As for characters, I particularly like Erina Nakiri from Food Wars. I've liked tsundere-type characters for a long time, especially characters who have a somewhat proud or elegant personality.`,
      `In general, I prefer stories with a rich world and detailed settings.`,
      `I don't just want to see characters fight. I like stories where the world, characters, and background have a lot of depth.`,
      `I also really like stories that I can read many times.`,
      `If I read something ten times and get bored, I don't value it as highly as a story that I can read again and again and still discover something new.`,
      `For me, a really good story is one that becomes more interesting the more you think about it.`,
    ],
  },
  {
    id: 11,
    title: "Why I Like Deep Stories",
    paragraphs: [
      `I like stories that have a lot of depth.`,
      `For me, a good story isn't something that I read once and completely understand. I like stories that make me notice new things when I read them again.`,
      `I especially enjoy stories with detailed world-building, interesting characters, and carefully designed settings.`,
      `I don't necessarily need a story to be extremely complicated. What matters to me is that the details feel connected and meaningful.`,
      `For example, when I read a story for the second or third time, I might notice something about a character that I didn't notice before. Then I can understand an earlier scene differently.`,
      `That's one of the most enjoyable things about reading.`,
      `I also like stories that feel like the author has spent a lot of time thinking about them.`,
      `When I finish a book and think, "I never would have thought about it that way," that's a really satisfying experience.`,
      `So I tend to value depth and rereadability more than just having an exciting plot.`,
    ],
  },
  {
    id: 12,
    title: "How I Discovered VTubers",
    paragraphs: [
      `I've been watching VTubers for quite a long time.`,
      `I think I started watching them around the time I was about to enter high school, although I don't remember the exact timing.`,
      `I probably discovered them because some VTuber videos appeared in my recommendations.`,
      `At first, I didn't watch many live streams. I also wasn't used to watching videos that were more than an hour long.`,
      `But gradually, I became interested in live streams.`,
      `One thing I like about VTubers is that you can learn about their personality over a long period of time.`,
      `For example, they might play a game while talking naturally. By listening to them for several hours, you gradually get a sense of what kind of person they are.`,
      `I think that's different from watching a short video.`,
      `Sometimes, when I'm feeling negative or tired, watching a familiar VTuber can also help me relax.`,
      `I've been watching VTubers for many years now, and I think I'm also interested in the live-streaming format itself.`,
    ],
  },
  {
    id: 13,
    title: "VTubers and YouTube",
    paragraphs: [
      `I've been watching VTubers for a long time, but recently I've been thinking more carefully about how I use YouTube.`,
      `I don't necessarily think watching a long live stream is a bad thing. If it's something I'm genuinely interested in, I can watch it for a long time and really enjoy it.`,
      `The problem is when I start watching recommended videos one after another.`,
      `There's a big difference between choosing something I want to watch and simply watching whatever YouTube recommends to me.`,
      `Sometimes I open a short video that doesn't even interest me very much, watch it for less than a minute, and then immediately move on to another one.`,
      `I feel like this can gradually take away my attention.`,
      `So recently, I've been trying to think more about what I actually want to watch.`,
      `I think the problem isn't really "watching content." It's more about whether I'm choosing the content myself or just following recommendations automatically.`,
      `That's something I'm still trying to manage.`,
    ],
  },
  {
    id: 14,
    title: "Smartphones and Concentration",
    paragraphs: [
      `Recently, I've been using my smartphone more than I would like.`,
      `I've noticed that when I spend too much time on my phone, it's harder for me to concentrate on things like reading and drawing.`,
      `Interestingly, there was a period when I barely used my smartphone. During that time, I was able to concentrate much better, and I made a lot of progress with my drawing.`,
      `I also used to write down what I did during the day in a notebook. That helped me notice how I was spending my time and change my behavior.`,
      `This made me realize that smartphones are very useful, but they can also easily interrupt my attention.`,
      `At the same time, I don't think all screen time is bad.`,
      `For example, I can enjoy watching a VTuber's live stream for a long time if I actually chose to watch it.`,
      `So for me, the important thing is not simply reducing screen time. I want to be more conscious about how I use my attention.`,
      `I'd rather spend my time reading, drawing, or watching something I genuinely enjoy than constantly switching between random videos.`,
    ],
  },
  {
    id: 15,
    title: "How I Have Changed",
    paragraphs: [
      `I think one of the biggest changes in me is how I approach drawing.`,
      `When I was a child, I simply liked drawing. I drew manga characters and came up with ideas for my own stories.`,
      `However, I mostly relied on what felt right. I often drew characters from the front, and I didn't really understand how the human body was structured.`,
      `When I started drawing again at university, I decided to study more seriously.`,
      `I read books about anatomy, human proportions, poses, and backgrounds. I tried to understand why something looked natural instead of simply copying it.`,
      `As a result, I became much better at drawing.`,
      `One important change is that I can now think about a pose myself and draw something reasonably natural without simply copying a photograph.`,
      `I think that's a big improvement.`,
      `In a way, I changed something that was simply a hobby I liked into a skill that I could consciously study and improve.`,
      `I'd like to continue doing that in the future.`,
    ],
  },
  {
    id: 16,
    title: "What I Want to Create",
    paragraphs: [
      `In the future, I want to create something that I can call my own work.`,
      `First, I want to become better at drawing characters. In particular, I want to be able to draw anime-style characters naturally.`,
      `I also want to learn how to put several characters into the same scene.`,
      `That's important to me because I don't just want to draw individual characters. I want to show relationships between characters through their expressions, poses, and interactions.`,
      `Eventually, I'd like to create something like a manga or a slice-of-life story.`,
      `It doesn't necessarily have to be a manga. It could be a novel, an illustration, or some other form of creative work.`,
      `The format isn't the most important thing to me.`,
      `What I really want is to finish one complete work.`,
      `I want to look at it after I've finished and think, "I actually made this."`,
      `It doesn't have to become famous or receive a lot of attention.`,
      `I'd be happy if I could simply create something that I'm personally satisfied with.`,
    ],
  },
  {
    id: 17,
    title: "My Values",
    paragraphs: [
      `I think I value going deeply into the things I really like.`,
      `I'm not particularly interested in doing many things just so that other people will think I'm interesting.`,
      `I'd rather spend a lot of time reading, drawing, learning, and creating something that I personally care about.`,
      `For example, when I find an interesting subject, I like learning more about it instead of just learning the basics and moving on.`,
      `I think the same thing applies to creative work. I don't just want to draw one picture and move on to something else. I'd like to keep improving and eventually finish a complete work.`,
      `At the same time, I've learned something from looking back on my university life.`,
      `Going deep into my hobbies is important to me, but simply thinking about things isn't enough. Sometimes I need to actually take action.`,
      `So these days, I think both things are important: going deep into the things I love, and actually doing something about my interests.`,
      `I don't want to give up my quiet, indoor hobbies. But I also want to become a little more willing to take action.`,
    ],
  },
];
